#!/bin/sh

echo 'Working directory: '$(pwd)

echo -n '\e[0;33m'
echo -n 'Checking exist `_trash` directory... '
echo -n '\e[m';
if [ -d "_trash" ] ;then
    echo -n '\e[1;32m';
    echo -n 'OK';
    echo '\e[m';
else
    echo -n '\e[0;33m'
    echo -n 'Creating... '
    echo -n '\e[m';
    echo -n $(mkdir -p _trash);

    if [ -d "_trash" ] ;then
        echo -n '\e[1;32m';
        echo -n 'OK';
        echo '\e[m';
    fi
fi

if [ $(jobs|wc -l) -eq 0 ] ; then

rename -v 's/\?.*//g' *

find -name '*.AVIF' -exec rename .AVIF .avif {} \;
find -name '*.WEBP' -exec rename .WEBP .webp {} \;
find -name '*.HEIC' -exec rename .HEIC .heic {} \;
find -name '*.jpeg' -exec rename .jpeg  .jpg {} \;
find -name '*.jeif' -exec rename .jeif  .jpg {} \;
find -name '*.JPEG' -exec rename .JPEG  .jpg {} \;
find -name '*.JEIF' -exec rename .JEIF  .jpg {} \;
find -name '*.JPG'  -exec rename  .JPG  .jpg {} \;
find -name '*.PNG'  -exec rename  .PNG  .png {} \;
find -name '*.GIF'  -exec rename  .GIF  .gif {} \;

for i in *.heic; do
    if [ ! -f "${i}" ] ;then
        echo '\e[1;31mFile or Directory has not found: '${i}'\e[m'
        continue;
    fi
    echo -n '\e[1;34m';
    echo -n $(dirname $(pwd))/;
    echo -n '\e[1;33m';
    echo -n $(basename $(pwd))/;
    echo -n '\e[1;36m';
    echo -n ${i};
    echo '\e[m';
    LC_ALL=C convert \
        "${i}" \
        "${i//.heic/.png}" && \
        LC_ALL=C mv "${i}" _trash/;
done

for i in *.png *.jpg G*; do
    if [ ! -f "${i}" ] ;then
        echo '\e[1;31mFile or Directory has not found: '${i}'\e[m'
        continue;
    fi
    echo -n '\e[1;34m';
    echo -n $(dirname $(pwd))/;
    echo -n '\e[1;33m';
    echo -n $(basename $(pwd))/;
    echo -n '\e[1;36m';
    echo -n ${i};
    echo '\e[m';
    LC_ALL=C ffmpeg \
        -hide_banner \
        -i "${i}" \
        -y "${i%.*}.webp" && \
        LC_ALL=C mv "${i}" _trash/;
done

mv wget-log* _trash/

fi

uid=1000
gid=${uid}
chown -R ${uid} ./
chgrp -R ${gid} ./
